### ISSUE TITLE
Donation perks break on servers

### ISSUE THREAD

**Issue by Claycorp** [Modding-Legacy/Aether-Legacy#160]
So rather than no perks and being able to play nobody can connect at all. Hell the server locks up on trying to get your perks which tells me you do it in the main server thread. THAT'S A HUGE, STUPID MISTAKE.

If you want to add things that rely on outside data DO IT SAFE and DON'T DO IT IN THE MAIN SERVER THREADS.

https://pastebin.com/SRTHC780

**Comment by topher2010** [comment]
Our players can't connect to our server with this mod in either.

**Comment by KingPhygieBoo** [comment]
The official server functions fine, and it has the latest version.

**Comment by Claycorp** [comment]
@topher2010 You can't do anything other than remove the mod from the server to let people get on again.
I would say just turn off the donation perks but the config options for the mod are lacking.

**Comment by Claycorp** [comment]
@KingPhygieBoo Does the official server host the file for the donation perks? If it does then that's why it works fine.

Also the official server working fine doesn't matter when the system used to check the perks in the first place is flawed beyond belief.

**Comment by KingPhygieBoo** [comment]
No, it does not. The donation perks go through Gilded Games' servers, the authors of Aether II.

**Comment by Claycorp** [comment]
There must be issues with internet routing then but that still doesn't excuse the lack of an option to turn it off, that it doesn't fail safely or that it runs in the main server thread.

**Comment by Lachney** [comment]
Hey, @Claycorp will definitely investigate this issue. 😌 
You are right, having non-accessible external data at the time and resulting in it not letting you connect to your server is pretty annoying, hehe! We'll get that patched up for you, booboo.

**Comment by dries007** [comment]
When everything works like it's supposed to, this delays a player's login with ~200ms to ~400ms. It halts the network thread causing lag spikes, and if the call fails, for whatever reason, it can lock up the server for however long Java is configured to time out.

Since you are doing nothing in your code that is timing critical, **please for the love of the flying spaghetti monster, use a thread**. You can just put [these lines](https://github.com/Modding-Legacy/Aether-Legacy/blob/58694a478db1d7b1bdcad8fad8ace8c15f0cb030/src/main/java/com/legacy/aether/common/player/PlayerAetherEvents.java#L154-L156) in a thread and use the addScheduledTask method of the MinecraftServer object to send the packet via the main server thread, so you don't exchange one crash for another. I would PR it, but I don't have the time to properly test it.
