### ISSUE TITLE
Aether Portal Suffocation bug

### ISSUE THREAD

**Issue by Razinoid** [Modding-Legacy/Aether-Legacy#279]
While playing on a private server, after teleporting to Aether, portal can teleport you back.
On slower systems or/and servers Aether portal teleports you back before you can exit. (even when holding movement keys).

Aether dimension also starts to lag the client after repeating these teleportation cycles until the client crashes or i get disconnected from server.

Steps:
1.Step in the portal
2.Wait

After restarting the server, first teleport didn't teleport me back, after next teleport bug reappeared. 

Edit:
I May have chased the damage part of the bug down.
Damage was caused by what i would call "Portal location-destination mismatch".
It appears that Portal first teleports you to a desired destination which happens to be a wall, before moving you to the nearest portal. Due to a slow server and/or system player spends long enough time to take damage.

I removed descriptions about the damage bug as i am quite sure this is how it works.
Still the fact i sometimes cant exit portal is rather annoying.

**Comment by Leafygreens97** [comment]
After testing this on a server with 2GB of RAM, I can confirm this as well. Entering the Aether is fine; it's trying to get back out through the portal that causes this issue. I can also confirm the "destination mismatch", as after being disconnected and logging back in I would find myself in a place a few blocks away from the portal, still in the Aether.

**Comment by Lachney** [comment]
Does this issue still happen the latest version of Aether Legacy? @Leafygreens97 @Razinoid

**Comment by Razinoid** [comment]
Checking for me it right now is extremely inconvenient, as the server i was playing on is now offline and I was using extremely underpowered hardware at that time. But ill see what I can do.

**Comment by Lachney** [comment]
Lol better late than never @razinoid

**Comment by Lachney** [comment]
After getting annoyed not being able to reproduce this issue I have concluded many things since.
This was only tested with Minecraft 1.12.2 on Forge
* This issue occurs more frequently when the server is lagging
* This issue does not occur when using the portal in an open area because of the weird offset after teleporting.
* This does not happen in singleplayer
* This does also happen with the nether portal
* You can get stuck in portal loops with both portals.

Anyways, I did lots of testing with this, and concluded it just looks like a weird vanilla bug (specfically when servers are lagging) and when the portal is not in an open area. When you are teleporting through a portal, It sends you through the dimension a bit off where the portal is, and if there are blocks there you will take suffocation damage.

Take a look at this image here, this is someone I had teleporting back to the overworld and the server was purposely being throttled, he is then teleported into the overworld with a weird offset (on his side he sees the Loading Terrain" screen, then he is flung into the portal.  If there are blocks where he is teleporting in that weird offset, then he will take suffocation damage and potentially get stuck in a portal loop.

![portal](https://i.qua.cx/apdFQ.png)]

Unfortunately there is nothing we can do (as of now) to fix it since it seems to be a weird issue with traveling dimensions with vanilla potentially, however if you wish to not take any form of damage and it is a huge problem for you, the best case is to:

* Try and improve the server, connection, or any form of thing that can lag you
* If you cannot improve on the above, use the portal in the most open area possible to prevent this
