### ISSUE TITLE
[Bug] Crash on World Enter with hooked

### ISSUE THREAD

**Issue by Darkmega18** [Modding-Legacy/Aether-Legacy#384]
**Aether Legacy Version(s)**
aether_legacy-1.12.2-v1.4.0.jar 

**Minecraft Version(s) Affected:**
1.12.2

**Extra Mod(s):**
A lot. see the provided logs further down.

**Describe the bug**
I've sent to hooked since it starts with reference to hooked, but both also refer to the api here. But basically I was doing a blanket of updates to all my mods after a long time away and updating my modpack, "Transcendence". Fortunately I managed to make the pack load. Unfortunately upon creating a completely fresh world in creative to make sure stuff runs and test a few things the game crashed before the world even loaded :V. 

The crash created two versions of itself in the crash logs folder too. A client and a server version and is related to hooked too. I've posted it to their issues also and will cross link it.

Here (client):
https://pastebin.com/mrM1sqYu

and Here (server):
https://pastebin.com/SkyRfrQ2

Loading the game without aether legacy (after exploding once due to my configured tough as nails configs :V) allows the game to run, however aether legacy and hooked are kinda required as part of the quests of my modpack so I can't update without this fixed unfortunately. :< So please, have a look at it.

(link to hookeds side of my report) https://github.com/thecodewarrior/Hooked/issues/29

**Comment by thecodewarrior** [comment]
My mod is written in Kotlin, which has explicit nullability and adds runtime null checks everywhere outside code can come in contact with Kotlin code, and that includes the `getCapability` method's parameters. Somehow, `AETHER_PLAYER` in [AetherAPI](https://github.com/Modding-Legacy/Aether-Legacy/blob/1.12.2/src/main/java/com/legacy/aether/api/AetherAPI.java#L66) is null, which eventually trickles down to Hooked where it crashes. Often these bugs go unnoticed because capabilities use an identity equals check, and `null == null`. However, if two mods both exhibit the bug then whichever registered first will return its capability for both, which will also lead to crashes.

Most likely the capability isn't being registered properly somewhere.
